"""Tests for the Markdown renderer (PR comments / CI job summaries)."""

from __future__ import annotations

import json
import re
from pathlib import Path

from typer.testing import CliRunner

from pqcscan.cli import app
from pqcscan.config import PqcConfig
from pqcscan.output.markdown import to_markdown
from pqcscan.scanner.engine import run_scan

runner = CliRunner()
FIXTURES = Path(__file__).parent / "fixtures" / "python"


def _result(path: Path = FIXTURES / "vulnerable_rsa.py", **cfg_kwargs):
    cfg = PqcConfig.default()
    cfg.severity_threshold = "low"
    for key, value in cfg_kwargs.items():
        setattr(cfg, key, value)
    return run_scan([path], cfg)


def _table_rows(markdown: str) -> list[str]:
    """Body rows of the findings table only (not the counts table above it)."""
    lines = markdown.splitlines()
    try:
        start = lines.index("### Findings")
    except ValueError:
        return []
    rows = []
    for line in lines[start:]:
        if line.startswith("### ") and line != "### Findings":
            break
        if line.startswith("| ") and not line.startswith(("| ---", "| Severity")):
            rows.append(line)
    return rows


def test_clean_scan_says_so():
    md = to_markdown(_result(FIXTURES / "safe_code.py"))
    assert "No quantum-vulnerable cryptography detected" in md
    assert "### Findings" not in md


def test_counts_table_matches_the_result():
    result = _result()
    md = to_markdown(result)
    counts = result.counts_by_severity()
    assert f"| {counts['critical']} | {counts['high']} |" in md
    assert f"**{result.total}**" in md


def test_every_finding_gets_a_row():
    result = _result()
    md = to_markdown(result, detail_limit=0)
    rows = _table_rows(md)
    assert len(rows) == result.total
    assert all("`PQC" in row for row in rows)


def test_rows_are_relative_paths():
    md = to_markdown(_result())
    assert "vulnerable_rsa.py:" in md
    assert str(FIXTURES) not in md


def test_details_blocks_carry_migration_guidance():
    md = to_markdown(_result(), detail_limit=2)
    assert md.count("<details>") == 2
    assert "**Migrate to:**" in md
    assert "FIPS 203" in md


def test_table_limit_reports_what_it_omitted():
    result = _result()
    md = to_markdown(result, table_limit=1, detail_limit=0)
    assert len(_table_rows(md)) == 2  # one finding + the "more" row
    assert f"{result.total - 1} more finding(s) not shown" in md


def test_detail_limit_reports_what_it_omitted():
    result = _result()
    md = to_markdown(result, detail_limit=1)
    assert md.count("<details>") == 1
    assert f"{result.total - 1} more in the full report" in md


def test_zero_limits_mean_no_cap():
    result = _result()
    md = to_markdown(result, table_limit=0, detail_limit=0)
    assert len(_table_rows(md)) == result.total
    assert "not shown" not in md


def test_pipe_characters_are_escaped(tmp_path):
    """A snippet or algorithm containing '|' must not break the table."""
    src = tmp_path / "pipes.py"
    src.write_text("import hashlib\nh = hashlib.new('sha1')\n", encoding="utf-8")
    result = _result(src)
    for finding in result.findings:
        finding.algorithm = "SHA-1 | legacy"
    md = to_markdown(result, detail_limit=0)
    for row in _table_rows(md):
        # 5 columns -> 6 pipes; an unescaped one in the content would add more.
        assert len(re.findall(r"(?<!\\)\|", row)) == 6


def test_suppressed_and_baselined_counts_appear():
    result = _result(FIXTURES / "suppressed_rsa.py")
    md = to_markdown(result)
    assert "suppressed inline" in md


def test_code_fence_uses_the_file_language():
    md = to_markdown(_result(), detail_limit=1)
    assert "```python" in md


def test_footer_is_appended_when_given():
    md = to_markdown(_result(), footer="_generated by CI_")
    assert md.rstrip().endswith("_generated by CI_")


# --------------------------------------------------------------------------- #
# CLI wiring
# --------------------------------------------------------------------------- #


def test_cli_markdown_format():
    result = runner.invoke(
        app, ["scan", str(FIXTURES / "vulnerable_rsa.py"), "-o", "markdown", "-s", "low"]
    )
    assert result.exit_code == 0
    assert result.stdout.startswith("## 🔐 pqc-scan")
    assert "| Severity | Rule |" in result.stdout


def test_cli_report_command_accepts_markdown(tmp_path):
    out = tmp_path / "report.md"
    result = runner.invoke(
        app,
        ["report", str(FIXTURES / "vulnerable_rsa.py"), "--format", "markdown",
         "--output-file", str(out)],
    )
    assert result.exit_code == 0
    assert out.read_text(encoding="utf-8").startswith("## 🔐 pqc-scan")


def test_cli_rejects_an_unknown_format():
    result = runner.invoke(
        app, ["scan", str(FIXTURES / "vulnerable_rsa.py"), "-o", "rst"]
    )
    assert result.exit_code == 2


def test_markdown_output_file_does_not_also_print(tmp_path):
    out = tmp_path / "report.md"
    result = runner.invoke(
        app,
        ["scan", str(FIXTURES / "vulnerable_rsa.py"), "-o", "markdown",
         "-f", str(out), "-s", "low"],
    )
    assert result.exit_code == 0
    assert "| Severity | Rule |" not in result.stdout
    assert out.is_file()


def test_json_and_markdown_agree_on_totals():
    as_json = runner.invoke(
        app, ["scan", str(FIXTURES / "vulnerable_rsa.py"), "-o", "json", "-s", "low"]
    )
    total = json.loads(as_json.stdout)["summary"]["total"]
    as_md = runner.invoke(
        app, ["scan", str(FIXTURES / "vulnerable_rsa.py"), "-o", "markdown", "-s", "low"]
    )
    assert f"**{total}**" in as_md.stdout


def test_a_snippet_containing_a_fence_does_not_escape_the_code_block(tmp_path):
    """`hashlib.md5(b"```")` is valid Python; a fixed 3-backtick fence would be
    closed by it, spilling the rest of the report into the surrounding page."""
    src = tmp_path / "fence.py"
    src.write_text('import hashlib\nh = hashlib.md5(b"```")\n', encoding="utf-8")
    md = to_markdown(_result(src))
    block = md[md.index("<details>"):]
    fences = re.findall(r"^(`{3,})", block, re.M)
    assert len(fences) == 2 and fences[0] == fences[1]
    assert len(fences[0]) > 3, "the fence must be longer than the content's run"


def test_the_fence_grows_with_the_longest_backtick_run(tmp_path):
    src = tmp_path / "fence.py"
    src.write_text('import hashlib\nh = hashlib.sha1(b"````x")\n', encoding="utf-8")
    md = to_markdown(_result(src))
    fences = re.findall(r"^(`{3,})", md[md.index("<details>"):], re.M)
    assert all(len(f) == 5 for f in fences)


def test_details_summary_escapes_html():
    """The summary is raw HTML; an unescaped path or name would inject markup."""
    result = _result()
    for finding in result.findings:
        finding.algorithm = "<b>RSA</b>"
        finding.file_path = "src/<script>.py"
    md = to_markdown(result, detail_limit=1)
    summary = [l for l in md.splitlines() if l.startswith("<summary>")][0]
    assert "<script>" not in summary
    assert "&lt;script&gt;" in summary


def test_carriage_returns_do_not_break_table_rows():
    result = _result()
    for finding in result.findings:
        finding.algorithm = "RSA\r\n2048"
    md = to_markdown(result, detail_limit=0)
    for row in _table_rows(md):
        assert "\r" not in row
